Feature/login
agnieszkapawska/flashcards pull request #7
Opened 2019-09-23 11:30 UTC by agnieszkapawska

Very basic registration and login.

2019-09-24 18:54 UTC, krzysztofpawski requested changes

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/dtos/UserLoginDto.java
> +public class UserLoginDto {
```suggestion
public class UserCredentialsDto {
```

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/dtos/UserSaveDto.java
> +
This new line is not needed.

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/api/controllers/UserController.java
> +    public ResponseEntity<UserSaveResponseDto> registerUser(@RequestBody UserSaveDto userSaveDto) {
```suggestion
    public ResponseEntity<UserRegistrationResponseDto> registerUser(@RequestBody UserSaveDto userSaveDto) {
```

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/facades/FlashcardFacade.java
> +            User user = userService.findById(Long.parseLong(flashcardSaveDto.getUserId()));
Is there any reason to keep `flashcardSaveDto.userId` of type `String`? Maybe let's change it to `Long` and then you don't need to cast it here.

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/facades/UserFacade.java
> +        User user = userService.confirmCredentials(username, password).orElse(new User());
`new User()` in case of bad credentials? There should be some exception thrown and appropriate HTTP status returned.

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/models/Role.java
> +@Table(name = "role")
Flashcard, QuestionTag but role, user... Maybe we could keep one convention for naming tables?

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/services/authorization/UserServiceImpl.java
> +                DataIntegrityViolationException exception) {
Move it to previous line please :)

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/services/authorization/UserServiceImpl.java
> +                userRepository.findByUserName(username).orElseThrow(() -> new EntityCouldNotBeFoundException(username + " couldn't be found"));
Maybe let's move `.orElse...` to next line

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/facades/UserFacade.java
> +        User user = userService.confirmCredentials(username, password).orElse(new User());
Also, please remember the difference between `orElse` and `orElseGet` and use it wisely.

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/services/authorization/UserServiceImpl.java
> +            Optional<Role> roleOptional = roleRepository.findByName(roleName);
```
Role role = roleRepository.findByName(roleName).orElseGet { 
    Role role = new Role(roleName);
    roleRepository.save(role);
    return role;
};
roles.add(role);
```

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/utils/CustomAuthenticationProvider.java
> +public class CustomAuthenticationProvider implements AuthenticationProvider {
This class is still needed?

2019-09-24 18:54 UTC, krzysiekpawski commented on src/main/java/com/agnieszkapawska/flashcards/infrastructure/configurations/SecurityConfiguration.java
> +    protected void configure(HttpSecurity httpSecurity) throws Exception {
This class is still needed?

2019-09-29 09:05 UTC, agnieszkapawska commented on src/main/java/com/agnieszkapawska/flashcards/infrastructure/configurations/SecurityConfiguration.java
> +    protected void configure(HttpSecurity httpSecurity) throws Exception {
yes :D

2019-12-01 16:43 UTC, krzysztofpawski approved these changes

2019-12-01 16:43 UTC, krzysztofpawski commented on src/main/java/com/agnieszkapawska/flashcards/domain/services/authorization/UserServiceImpl.java
> +                        Role role1 = new Role(roleName);
Adding numbers is not a good practice. 1 doesn't say anything. Maybe `newRole` or `createdRole`?

2019-12-01 16:47 UTC, merged